/* eslint-disable max-classes-per-file */
import { BaseDto as ApiBaseDto } from '@goodt-common/infra';

/**
 * @todo Purge Collection* classes
 */
export class BudgetEntityDto extends ApiBaseDto {}
export class BudgetDataEntityDto extends ApiBaseDto {}
export class BudgetItemEntityDto extends ApiBaseDto {}
export class BudgetItemGroupEntityDto extends ApiBaseDto {}
export class BudgetSourceEntityDto extends ApiBaseDto {}
export class ClassroomEntityDto extends ApiBaseDto {}
export class ContentTypeEntityDto extends ApiBaseDto {}
export class ContractSubjectEntityDto extends ApiBaseDto {}
export class DocumentTypeEntityDto extends ApiBaseDto {}
export class DurationEntityDto extends ApiBaseDto {}
export class LearningCourseEntityDto extends ApiBaseDto {}
export class LearningCourseAnnouncementEntityDto extends ApiBaseDto {}
export class LearningCourseBudgetItemEntityDto extends ApiBaseDto {}
export class LearningCourseCatalogEntityDto extends ApiBaseDto {}
export class LearningCourseDocumentTypeEntityDto extends ApiBaseDto {}
export class LearningCourseGroupEntityDto extends ApiBaseDto {}
export class LearningCourseGroupBindingDto extends ApiBaseDto {}
export class LearningCourseMessageBindingDto extends ApiBaseDto {}
export class LearningCourseSimilarEntityDto extends ApiBaseDto {}
export class LearningCourseStudyDirectionEntityDto extends ApiBaseDto {}
export class LearningCourseTypeEntityDto extends ApiBaseDto {}
export class LearningCourseCuratorEntityDto extends ApiBaseDto {}
export class LearningCoursePartyEntityDto extends ApiBaseDto {}
export class LearningCourseStepEntityDto extends ApiBaseDto {}
export class LearningFormEntityDto extends ApiBaseDto {}
export class LearningProgramEntityDto extends ApiBaseDto {}
export class LearningProgramCatalogEntityDto extends ApiBaseDto {}
export class LearningProgramDocumentTypeEntityDto extends ApiBaseDto {}
export class LearningProgramLearningCourseBindingDto extends ApiBaseDto {}
export class LearningProgramLearningCourseDependencyEntityDto extends ApiBaseDto {}
export class LearningProgramLearningCoursePartyEntityDto extends ApiBaseDto {}
export class LearningStudyGroupDto extends ApiBaseDto {}
export class LearningStudyGroupNumeratorEntityDto extends ApiBaseDto {}
export class MessageEntityDto extends ApiBaseDto {}
export class StatusEntityDto extends ApiBaseDto {}
export class StudyDegreeGroupEntityDto extends ApiBaseDto {}
export class StudyDirectionEntityDto extends ApiBaseDto {}
export class StudyExpertEntityDto extends ApiBaseDto {}
export class StudyExpertContractEntityDto extends ApiBaseDto {}
export class StudyExpertContractRateEntityDto extends ApiBaseDto {}
export class StudyExpertContractTypeEntityDto extends ApiBaseDto {}
export class StudyGrantEntityDto extends ApiBaseDto {}
export class StudyGrantAllocationEntityDto extends ApiBaseDto {}
export class StudyGrantAllocationStudyExpertEntityDto extends ApiBaseDto {}
export class StudyGrantAllocationStudyStudentEntityDto extends ApiBaseDto {}
export class StudyLocationEntityDto extends ApiBaseDto {}
export class StudyPerformanceTypeEntityDto extends ApiBaseDto {}
export class StudyProviderEntityDto extends ApiBaseDto {}
export class StudyProviderContractEntityDto extends ApiBaseDto {}
export class StudyProviderRegionEntityDto extends ApiBaseDto {}
export class StudyProviderRegionCityEntityDto extends ApiBaseDto {}
export class StudyProviderTypeEntityDto extends ApiBaseDto {}
export class StudyDegreeEntityDto extends ApiBaseDto {}
export class StudyStudentEntityDto extends ApiBaseDto {}
export class StudyStudentEducationEntityDto extends ApiBaseDto {}
export class StudyStudentPerformanceEntityDto extends ApiBaseDto {}
export class SuggestionEntityDto extends ApiBaseDto {}
export class UserLearningCourseEntityDto extends ApiBaseDto {}
export class UserLearningCourseDocumentEntityDto extends ApiBaseDto {}
export class UserLearningCourseStepEntityDto extends ApiBaseDto {}
export class LearningCourseStudyExpertBindingDto extends ApiBaseDto {}
export class PageLearningCourseEntityDto extends ApiBaseDto {}
export class InfoDtoDto extends ApiBaseDto {}
