/* eslint-disable max-classes-per-file */
import { BaseDto as ApiBaseDto } from '@goodt-common/infra';

/**
 * @todo Purge Collection* classes
 */
export class EntityModelBudgetEntityDto extends ApiBaseDto {}
export class EntityModelBudgetDataEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelBudgetItemEntityDto extends ApiBaseDto {}
export class EntityModelBudgetItemEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelBudgetItemGroupEntityDto extends ApiBaseDto {}
export class EntityModelBudgetItemGroupEntityDto extends ApiBaseDto {}
export class EntityModelBudgetSourceEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelClassroomEntityDto extends ApiBaseDto {}
export class EntityModelClassroomEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelContentTypeEntityDto extends ApiBaseDto {}
export class EntityModelContentTypeEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelContractSubjectEntityDto extends ApiBaseDto {}
export class EntityModelContractSubjectEntityDto extends ApiBaseDto {}
export class EntityModelDocumentTypeEntityDto extends ApiBaseDto {}
export class EntityModelDurationEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseAnnouncementEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseBudgetItemEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseCatalogEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseCuratorEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseDocumentTypeEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseGroupEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseLearningCourseGroupEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseMessageEntityDto extends ApiBaseDto {}
export class EntityModelLearningCoursePartyEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseSimilarEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseStudyDirectionEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseTypeEntityDto extends ApiBaseDto {}
export class LearningCourseCuratorEntityDto extends ApiBaseDto {}
export class CollectionModelLearningCourseLearningCourseGroupEntityDto extends ApiBaseDto {}
export class CollectionModelLearningCoursePartyEntityDto extends ApiBaseDto {}
export class EntityModelLearningCourseStepEntityDto extends ApiBaseDto {}
export class CollectionModelLearningCourseMessageEntityDto extends ApiBaseDto {}
export class EntityModelLearningFormEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramCatalogEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramDocumentTypeEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelLearningProgramLearningCourseEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramLearningCourseEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelLearningProgramLearningCourseDependencyEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramLearningCourseDependencyEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelLearningProgramLearningCoursePartyEntityDto extends ApiBaseDto {}
export class EntityModelLearningProgramLearningCoursePartyEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelLearningStudygroupEntityDto extends ApiBaseDto {}
export class EntityModelLearningStudygroupEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelLearningStudygroupNumeratorEntityDto extends ApiBaseDto {}
export class EntityModelLearningStudygroupNumeratorEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelMessageEntityDto extends ApiBaseDto {}
export class EntityModelMessageEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStatusEntityDto extends ApiBaseDto {}
export class EntityModelStatusEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyDegreeEntityDto extends ApiBaseDto {}
export class EntityModelStudyDegreeEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyDegreeGroupEntityDto extends ApiBaseDto {}
export class EntityModelStudyDegreeGroupEntityDto extends ApiBaseDto {}
export class EntityModelStudyDirectionEntityDto extends ApiBaseDto {}
export class EntityModelStudyExpertEntityDto extends ApiBaseDto {}
export class EntityModelStudyExpertContractEntityDto extends ApiBaseDto {}
export class EntityModelStudyExpertContractRateEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyExpertContractTypeEntityDto extends ApiBaseDto {}
export class EntityModelStudyExpertContractTypeEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyGrantEntityDto extends ApiBaseDto {}
export class EntityModelStudyGrantEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyGrantAllocationEntityDto extends ApiBaseDto {}
export class EntityModelStudyGrantAllocationEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyGrantAllocationStudyExpertEntityDto extends ApiBaseDto {}
export class EntityModelStudyGrantAllocationStudyExpertEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyGrantAllocationStudyStudentEntityDto extends ApiBaseDto {}
export class EntityModelStudyGrantAllocationStudyStudentEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyLocationEntityDto extends ApiBaseDto {}
export class EntityModelStudyLocationEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyPerformanceTypeEntityDto extends ApiBaseDto {}
export class EntityModelStudyPerformanceTypeEntityDto extends ApiBaseDto {}
export class EntityModelStudyProviderEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyProviderContractEntityDto extends ApiBaseDto {}
export class EntityModelStudyProviderContractEntityDto extends ApiBaseDto {}
export class CollectionModelContractSubjectEntityDto extends ApiBaseDto {}
export class EntityModelStudyProviderRegionEntityDto extends ApiBaseDto {}
export class EntityModelStudyProviderRegionCityEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyProviderTypeEntityDto extends ApiBaseDto {}
export class EntityModelStudyProviderTypeEntityDto extends ApiBaseDto {}
export class CollectionModelStudyDegreeEntityDto extends ApiBaseDto {}
export class CollectionModelEntityModelStudyStudentEntityDto extends ApiBaseDto {}
export class EntityModelStudyStudentEntityDto extends ApiBaseDto {}
export class EntityModelStudyStudentEducationEntityDto extends ApiBaseDto {}
export class EntityModelStudyStudentPerformanceEntityDto extends ApiBaseDto {}
export class EntityModelSuggestionEntityDto extends ApiBaseDto {}
export class EntityModelUserLearningCourseEntityDto extends ApiBaseDto {}
export class EntityModelUserLearningCourseDocumentEntityDto extends ApiBaseDto {}
export class EntityModelUserLearningCourseStepEntityDto extends ApiBaseDto {}
export class LearningCourseStepEntityDto extends ApiBaseDto {}
export class LearningCourseStudyExpertBindingDto extends ApiBaseDto {}
export class BudgetEntityDto extends ApiBaseDto {}
export class CollectionModelUserLearningCourseDocumentEntityDto extends ApiBaseDto {}
export class CollectionModelSuggestionEntityDto extends ApiBaseDto {}
export class PageLearningCourseEntityDto extends ApiBaseDto {}
export class InfoDtoDto extends ApiBaseDto {}
